# Generated by Django 4.2.30 on 2026-09-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Жанр')),
                ('duration_min', models.PositiveIntegerField(verbose_name='Длительность, мин')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год выхода')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
                'ordering': ['title'],
            },
        ),
    ]
